# Generated by Django 4.0.3 on 2022-04-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор клиента')),
                ('lastName', models.CharField(max_length=20, verbose_name='Фамилия клиента')),
                ('firstName', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество клиента')),
                ('document', models.CharField(max_length=80, verbose_name='Документ, удостоверяющий личность')),
                ('serial', models.CharField(max_length=10, verbose_name='Серия документа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('region', models.CharField(max_length=30, verbose_name='Кем выдан документ')),
                ('born', models.DateField(verbose_name='Дата рождения')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фотография клиента')),
                ('passport', models.BooleanField(default=False, verbose_name='Наличие заграничного паспорта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название гостиницы')),
                ('type', models.IntegerField(verbose_name='Класс гостиницы (***, ****)')),
                ('address', models.CharField(max_length=100, verbose_name=' Адрес гостиницы')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор сотрудника')),
                ('lastName', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('firstName', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор маршрута')),
                ('routeName', models.CharField(max_length=30, verbose_name='Название маршрута')),
                ('country', models.CharField(max_length=30, verbose_name='Название страны')),
                ('period', models.IntegerField(default=0, verbose_name='Срок пребывания(дни)')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость путевки')),
                ('exempt', models.IntegerField(default=0, verbose_name='Скидка')),
                ('amount', models.IntegerField(default=0, verbose_name='Конечная стоимость')),
                ('returnCost', models.IntegerField(default=0, verbose_name='Неустойка')),
                ('dateStart', models.DateTimeField(verbose_name='Дата вылета')),
                ('town', models.CharField(max_length=20, verbose_name='Пункт маршрута')),
                ('count', models.IntegerField(verbose_name='Срок пребывания в пункте маршрута')),
                ('startDate', models.DateTimeField(verbose_name='Дата прибытия в пункт маршрута')),
                ('stopDate', models.DateTimeField(verbose_name='Дата убытия')),
                ('comment', models.TextField(verbose_name='Экскурсионная программа')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.hotel', verbose_name='Гостиница')),
                ('worker', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='agency.worker', verbose_name='Представитель на маршруте')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
