# Generated by Django 4.0.3 on 2022-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='clients',
            field=models.ManyToManyField(to='agency.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=80, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(upload_to='img', verbose_name='Фотография клиента'),
        ),
    ]
