# Generated by Django 4.0.3 on 2022-04-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_route_clients_alter_client_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='route',
            name='count',
        ),
        migrations.RemoveField(
            model_name='route',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='route',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stopDate',
        ),
        migrations.RemoveField(
            model_name='route',
            name='town',
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20, verbose_name='Пункт маршрута')),
                ('count', models.IntegerField(verbose_name='Срок пребывания в пункте маршрута')),
                ('startDate', models.DateTimeField(verbose_name='Дата прибытия в пункт маршрута')),
                ('stopDate', models.DateTimeField(verbose_name='Дата убытия')),
                ('comment', models.TextField(verbose_name='Экскурсионная программа')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.hotel', verbose_name='Гостиница')),
            ],
        ),
    ]
