# Generated by Django 4.0.3 on 2022-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_routepoint_options_routepoint_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='clients_count',
            field=models.SmallIntegerField(default=5, verbose_name='Количество людей на маршрут'),
        ),
    ]
