# Generated by Django 4.0.3 on 2022-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_route_clients_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='clients_count',
        ),
    ]
